name: cronjob

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Restore cached data
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/registry
          ~/.cache/pip
        key: ${{ runner.os }}-data
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt update
        sudo apt install -y graphviz libgraphviz-dev default-jdk
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run jobs
      env:
        DN42GITTOKEN: ${{ secrets.DN42GITTOKEN }}
      run: ./run.sh $DN42GITTOKEN
    - name: Save data
      uses: actions/cache/save@v4
      with:
        path: |
          ~/registry
          ~/.cache/pip
        key: ${{ runner.os }}-data
    - name: Deploy Result
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: publish
        folder: data
