name: cronjob

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: |
          ./registry
        key: ${{ runner.os }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt install -y graphviz
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run jobs
      run: ./run.sh
    - name: Deploy Result
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: publish
        folder: data
